function [phi0,phi0_der] = comp_phi0(Geom,x_leb,N_leb,e1)
% potential phi_0 and its normal derivative at s_n on Gamma_j generated by
% atomic charges in vacuum e1

M = Geom.M;
R = Geom.R;
C = Geom.centers;
charges = Geom.charges;

phi0 = zeros(N_leb,M);
phi0_der = zeros(N_leb,M);

% Case 5
if Geom.M == 1
    M = 6;
    C =  [0.2, 0.2, 0.2; 0.5, 0.5, 0.5; 0.8, 0.8, 0.8; -0.2, ...
              0.2, -0.2; 0.5, -0.5, 0.5; -0.8, -0.8, -0.8];
    charges = ones(6,1);
    for j = 1:Geom.M
        cj = Geom.centers(j,:);
        rj = Geom.R(j);
        x = ones(N_leb,1)*cj+rj*x_leb(:,:);
        for i = 1:M
            dist = sqrt(sum((x-ones(N_leb,1)*C(i,:)).^2,2));
            phi0(:,j) = phi0(:,j)+charges(i)./(e1.*dist);

            vec = (x-ones(N_leb,1)*C(i,:))./(dist*ones(1,3));
            der = sum(vec.*x_leb(:,:),2);
            phi0_der(:,j) = phi0_der(:,j)-charges(i)./(e1.*dist.^2).*(der);
        end
    end
    
    return
end



for j = 1:M
    cj = C(j,:);
    rj = R(j);
    x = ones(N_leb,1)*cj+rj*x_leb(:,:);
    for i = 1:M
        dist = sqrt(sum((x-ones(N_leb,1)*C(i,:)).^2,2));
        phi0(:,j) = phi0(:,j)+charges(i)./(e1.*dist);
        
        vec = (x-ones(N_leb,1)*C(i,:))./(dist*ones(1,3));
        der = sum(vec.*x_leb(:,:),2);
        phi0_der(:,j) = phi0_der(:,j)-charges(i)./(e1.*dist.^2).*(der);
    end
end



end